### ISSUE TITLE
[JDBC] Gradle build fails due to the common/JDBC module.

### ISSUE THREAD

**Issue by orendain** [h2oai/dai-deployment-templates#163]
`./gradlew build` results in an error, due to the `common/jdbc` module:

```
> Task :common:jdbc:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:jdbc:compileScala
> java.lang.NullPointerException (no error message)
```

Additionally, the version of `zinc` is `2.10.5`, while the major version of Scala being brought in is `2.11`.  Mixing major versions of scala packages often results in issues (plus zinc has been deprecated for a while) - this may or may not be related, I haven't done any digging for the issue above.

**Comment by nkpng2k** [comment]
hmmm @orendain seems like this works locally... and in cicd. Mac issue? In what environment are you attempting to compile?

**Comment by nkpng2k** [comment]
http://mr-0xc1:8080/job/dai-deployment-templates/job/master/65/ new job to verify jenkins.

**Comment by orendain** [comment]
Thanks @nkpng2k !  Since it works on your machine, I'll take a deeper look now to see why its not playing nice with my setup.  Is there a specific reason we're specifying that specific version of zinc instead of using the built in one?  Will report back, thanks!

**Comment by nkpng2k** [comment]
@orendain I seem to remember there being an issue that caused me to set zinc as different version than the expected scala... No idea why now anymore.
