### ISSUE TITLE
Gradle Version Update

### ISSUE THREAD

**Issue by sairaamv** [h2oai/dai-deployment-templates#170]
Hi @thirdwing , @nkpng2k , 

I did try showcasing local-rest-server in windows 10 datacenter and it works in gradle version 6.3. Please do let me know your thoughts. Any plans to update the gradle version? 

https://github.com/h2oai/dai-deployment-templates/blob/716249f7e720365469caafda9788e572e447a6b3/gradle/wrapper/gradle-wrapper.properties#L3

-- thanks

**Comment by nkpng2k** [comment]
I think probably updating to gradle 6.x is fine. I am slightly worried as to side effects that might occur with dai since this project is where we pull all our deployment templates from for dai. But honestly I doubt it would really cause much of an issue.

**Comment by thirdwing** [comment]
Sorry that I have very little knowledge on gradle.
