### ISSUE TITLE
Docker install on MAC failed 

### ISSUE THREAD

**Issue by quantum-fusion** [h2oai/dai-deployment-templates#228]
Hello,

I tried downloading and installing the Docker images on MAC, and it fails. (http://docs.h2o.ai/driverless-ai/latest-stable/docs/userguide/install/mac-osx.html)

I faced a number of issues with permissions and installation of the Docker image on MAC:

https://stackoverflow.com/questions/42784396/docker-error-error-processing-tar-fileexit-status-1-unexpected-eof

docker image prune

sudo chown -R 655 ./dai-docker-centos7-x86_64-1.9.1.1-10.0.tar 

docker import dai-docker-centos7-x86_64-1.9.1.1-10.0.tar 

docker import dai-docker-centos7-x86_64-1.9.1.1-10.0.tar 
sha256:1d9f15acd46f6a3dcd8a014520dfbd52337c3976a70c9e8594c9dfa122e01b9a

docker image tag 1d9f15acd46f6a3dcd8a014520dfbd52337c3976a70c9e8594c9dfa122e01b9a  h2oai/dai-centos7-x86_64:latest

docker images 

h2oai/dai-centos7-x86_64               latest          1d9f15acd46f   14 minutes ago   28GB

---

sudo docker run \
  --pid=host \
  --init \
  --rm \
  --shm-size=256m \
  -u `id -u`:`id -g` \
  -p 12345:12345 \
  -v `pwd`/data:/data \
  -v `pwd`/log:/log \
  -v `pwd`/license:/license \
  -v `pwd`/tmp:/tmp \
  h2oai/dai-centos7-x86_64:latest
MacBook-Pro:~/dai-1.9.1 quantum-fusion$ pwd
/Users/hottelet/dai-1.9.1
MacBook-Pro:~/dai-1.9.1 quantum-fusion$ ls
dai-docker-centos7-x86_64-1.9.1.1-10.0.tar	license						run.sh
data						log						tmp
MacBook-Pro:~/dai-1.9.1 quantum-fusion$ ./run.sh
Password:
docker: Error response from daemon: No command specified.
See 'docker run --help'.

I ran from the docker GUI without command line arguments, and still same result.

<img width="933" alt="Screen Shot 2021-04-02 at 2 08 30 PM" src="https://user-images.githubusercontent.com/10088099/113441822-f5171f00-93bc-11eb-93f3-246d89f65e7e.png">

**Comment by nkpng2k** [comment]
@quantum-fusion this is unrelated to the purpose of this repo. Closing. However I would encourage you to take a look here https://www.h2o.ai/community/home for link to join community slack channel. You will have greater access to issues regarding installing/configuring driverless ai

**Comment by nkpng2k** [comment]
Also, side note: there is a significant difference between `docker import` and `docker load`. As the docs state, please use: `docker load < dai-docker-centos7-x86_64-<version>.tar.gz`
